export const TALK_CREATE_ROOM = 'TALK_CREATE_ROOM' as 'TALK_CREATE_ROOM'
export const TALK_SET_ROOMS = 'TALK_SET_ROOMS' as 'TALK_SET_ROOMS'
export const TALK_SET_ROOM = 'TALK_SET_ROOM' as 'TALK_SET_ROOM'