export const CREATE_ACOUNT = 'LOGIN_CREATE_ACOUNT'
export const LOGIN_ACOUNT = 'LOGIN_USER_ACOUNT'
export const SET_USERDATA = 'LOGIN_SET_USERDATA'
export const CHANGE_USER_ISLOGIN = 'CHANGE_USER_ISLOGIN'