export const LOGIN_CREATE_ACOUNT = 'LOGIN_CREATE_ACOUNT' as 'LOGIN_CREATE_ACOUNT'
export const LOGIN_USER_ACOUNT = 'LOGIN_USER_ACOUNT' as 'LOGIN_USER_ACOUNT'
export const LOGIN_SET_USERDATA = 'LOGIN_SET_USERDATA' as 'LOGIN_SET_USERDATA'
export const LOGIN_CHANGE_USER_ISLOGIN = 'CHANGE_USER_ISLOGIN' as 'CHANGE_USER_ISLOGIN'