export const USER_UPDATE_USERDATA = 'USER_UPDATE_USERDATA' as 'USER_UPDATE_USERDATA'
export const USER_SET_USERDATA = 'USER_SET_USERDATA' as 'USER_SET_USERDATA'
export const USER_CHANGE_LOADING = 'USER_CHANGE_LOADING' as 'USER_CHANGE_LOADING'
